### ISSUE TITLE
First iteration of enemies (dummies)

### ISSUE THREAD

**Issue by Tisreece** [Tisreece/Bible-Bash#11]
We will need something to deal damage to to test that the damage system and our attacks are functioning as expected.
These enemies will merely need to be objects with the enemy tag assigned to them with a damage system component attached to them. No AI, animation or even sprites (outside of a white cube) need be attached to these dummies as our first iteration

**Comment by A-Middy** [comment]
Can set up tags against prefabs (top right). Can then refer to these within if statements etc. to work out what to do during collision.
